"""
Specialized data loading utilities for the Simple10 optimizer results.

This module provides functions for loading, processing, and correcting summary 
data specifically generated by the Simple10 optimizer. Simple10 works by generating
batches of 10 code samples per task, requiring specific post-processing to ensure 
metrics like pass@1 and batch statistics are correctly calculated.

Key functionalities:
- Load sample files with their associated batch IDs
- Extract sample-level information from task summaries
- Create placeholder data for missing tasks
- Compute correct aggregated metrics for Simple10 optimizer results
"""
import sys
from typing import Set

import polars as pl


def load_sample_file(file_path: str) -> pl.LazyFrame:
    with open(file_path, "r") as f:
        return pl.scan_ndjson(f).with_columns(samples_path=pl.lit(file_path))


def get_samples_with_batch_id(task_summaries: pl.DataFrame) -> pl.DataFrame:
    # Extract individual samples from the task summaries
    samples = (
        task_summaries.explode("results")
        .drop("dps", "dps_norm", "num_cpu_instructions", "cpu_time")
        .with_columns(results_copy=pl.col("results"))
        .unnest("results")
        .drop("batch_id", strict=False)
    )

    # Load all original sample files to get batch IDs
    # sample_paths = task_summaries.select("samples_path").unique()
    # sample_files_data = [
    #     load_sample_file(row["samples_path"])
    #     for row in sample_paths.iter_rows(named=True)
    # ]
    #
    # # Extract the batch IDs from the original sample files
    # ids_df = pl.concat(
    #     sample_files_data,
    #     how="vertical_relaxed",
    # ).unnest("extra_data").select("task_id", "sample_id", "batch_id").collect()
    #
    # # Create a mapping from sample_id to batch_id
    # sample_to_batch_mapping = ids_df.unique().select("sample_id", "batch_id").rows_by_key(
    #     "sample_id", unique=True
    # )
    # sample_to_batch_dict = {k: v[0] for k, v in sample_to_batch_mapping.items()}

    # Verify data integrity
    original_sample_count = len(samples)

    # Add batch IDs to the samples
    # samples_with_batch = samples.with_columns(
    #     batch_id=pl.col("sample_id").replace(sample_to_batch_dict)
    # )
    samples_with_batch = samples.with_columns(batch_id=pl.col("sample_id"))

    # Verify no data was lost or duplicated in the process
    assert original_sample_count == len(samples_with_batch), \
        f"Sample count mismatch: original={original_sample_count}, new={len(samples_with_batch)}"

    return samples_with_batch


def calculate_correctness(task_level_metrics: pl.DataFrame) -> pl.DataFrame:
    if "force_n_samples_with_prev_results" not in task_level_metrics.columns:
        print("force_n_samples_with_prev_results is not in columns, adding it", file=sys.stderr)
        task_level_metrics = task_level_metrics.with_columns(pl.lit(None).alias("force_n_samples_with_prev_results"))
    task_level_metrics = task_level_metrics.with_columns(pl.col("force_n_samples_with_prev_results").fill_null(False))

    DEFAULT_BATCH_COUNT = 40  # Is the default number of samples in evalopti, which the first iteration is going to have
    BATCH_SIZE = 10  # Fixed batch size for Simple10
    task_level_metrics = task_level_metrics.with_columns(
        max_batch_count=pl.when(pl.col("force_n_samples_with_prev_results")).then(pl.col("n_samples")).otherwise(
            pl.lit(DEFAULT_BATCH_COUNT))
    )
    print(task_level_metrics["max_batch_count"].unique())
    assert all([count in [5, 40] for count in task_level_metrics["max_batch_count"]])

    task_level_metrics = task_level_metrics.with_columns(
        # Regular pass@1: percentage of samples that passed within each batch
        pass_1=pl.col("nb_passed").truediv(pl.col("nb_samples")) * 100,

        # Global pass@1: percentage of total samples that passed
        pass_1_global=pl.col("nb_passed").truediv(pl.col("max_batch_count") * pl.lit(BATCH_SIZE)) * 100,
        pass_result_global=pl.col("nb_batch_passed").truediv(DEFAULT_BATCH_COUNT) * 100
    )
    return task_level_metrics


def get_empty_rows_for_missing_tasks(dataframe: pl.DataFrame, all_task_ids: Set[str]) -> pl.DataFrame:
    # Find which tasks are missing
    missing_task_ids = set(all_task_ids) - set(dataframe["task_id"].unique())

    # Columns to copy values from the existing dataframe
    metadata_columns = [
        "temperature", "samples_path", "accept_errored_samples_in_optimizer",
        "enforce_n_samples", "nb_workers_generation", "file", "config_id",
        "optimizer", "nb_workers", "model", "iteration", "n_samples",
        "force_n_samples_with_prev_results"
    ]

    # Build expressions to copy first value for each metadata column
    metadata_column_exprs = [
        pl.lit(dataframe[col].first()).alias(col) for col in metadata_columns
    ]

    # Columns to fill with zeros
    zero_value_columns = ["pass_1", "pass_1_global", "nb_samples", "nb_results", "nb_passed", "nb_profiled"]
    zero_column_exprs = [pl.lit(0).alias(col) for col in zero_value_columns]

    # Create the placeholder rows
    placeholder_rows = pl.DataFrame({"task_id": list(missing_task_ids)}).with_columns(
        metadata_column_exprs + zero_column_exprs
    ).with_columns(
        pl.col("samples_path", "file").cast(pl.Categorical)
    )

    return placeholder_rows


def add_empty_rows_for_missing_tasks(
        simple10_tasks: pl.DataFrame,
        all_task_ids: Set[str]
) -> pl.DataFrame:
    # Ensure we're operating on a single optimizer
    assert simple10_tasks["optimizer"].n_unique() == 1, \
        "This operation is only supported for one optimizer at a time"

    # Generate placeholders for each model/iteration partition
    placeholder_rows_list = []
    for partition_df in simple10_tasks.partition_by("model", "iteration"):
        placeholder_rows_list.append(
            get_empty_rows_for_missing_tasks(partition_df, all_task_ids)
        )

    # Combine the original data with the placeholders
    return pl.concat([simple10_tasks] + placeholder_rows_list, how="diagonal_relaxed")


def get_correct_simple10_task_summary(
        simple10_tasks: pl.DataFrame,
        all_task_ids: Set[str]
) -> pl.DataFrame:
    print(simple10_tasks.columns)
    # Get sample-level data with batch IDs
    samples_with_batch = get_samples_with_batch_id(simple10_tasks).with_columns(
        generated_this_iteration=True
    )
    # First, aggregate at the batch level
    batch_level_metrics = samples_with_batch.group_by(
        ["file", "task_id", "batch_id", "iteration"]
    ).agg(
        # Count metrics
        nb_samples=pl.len(),
        nb_results=pl.lit(1),  # Each batch counts as one result
        nb_passed=pl.col("passed").sum(),
        nb_profiled=pl.col("profiled").sum(),
        # best_sample=pl.col("sample_id").filter(
        #     pl.col("num_cpu_instructions") == pl.col("num_cpu_instructions").min()).first(),
        # Performance metrics - use best/worst as appropriate for the batch
        dps=pl.col("dps").max(),  # Best DPS in the batch
        dps_norm=pl.col("dps_norm").max(),
        cpu_time=pl.col("cpu_time").min(),  # Fastest time in the batch
        num_cpu_instructions=pl.col("num_cpu_instructions").min(),

        # Keep original data
        samples_path=pl.col("samples_path").first(),
        results=pl.col("results_copy")
    ).with_columns(nb_batch_passed=pl.col("nb_passed") > 0)

    # Then, aggregate at the task level
    task_level_metrics = batch_level_metrics.group_by(
        ["file", "task_id", "iteration"]
    ).agg(
        # Sum all count metrics
        pl.col("^nb_.*$").sum(),

        # Average performance metrics across batches
        pl.col("dps", "dps_norm", "cpu_time", "num_cpu_instructions").mean(),

        # Keep batch IDs for reference
        pl.col("batch_id"),
        # nb_batch=pl.col("batch_id").n_unique(),

        # Other metadata
        samples_path=pl.col("samples_path").first().cast(pl.Categorical),
        results=pl.col("results").flatten()
    )

    # Join with original data to preserve any other columns and drop redundant columns
    task_level_metrics = (
        task_level_metrics
        # .drop("nb_batch")
        .join(
            simple10_tasks,
            on=["task_id", "iteration", "samples_path"]
        )
        .drop("^.*right$")  # Drop columns with suffix "_right" from the join
    )

    task_level_metrics = calculate_correctness(task_level_metrics)

    # Fill in any missing tasks
    complete_metrics = add_empty_rows_for_missing_tasks(task_level_metrics, all_task_ids)

    return complete_metrics
